### ISSUE TITLE
Question: CUDA libraries support

### ISSUE THREAD

**Issue by VarLad** [CHIP-SPV/chipStar#522]
From the "About":

>  chipStar is a backend infrastructure for HIP/CUDA running on SPIR-V via OpenCL or Level Zero APIs. 

Does this include support for CUDA libraries like cuBLAS, cuDNN etc?
I ask this question because, NVK (open source NVIDIA Vulkan driver) is going along at a good rate, and CUDA won't be available on it, even after completion. 
I wonder if chipStar can just become the CUDA runtime on these open source drivers (by providing an OpenCL backend running atop the RustiCL driver)

**Comment by pjaaskel** [comment]
> Does this include support for CUDA libraries like cuBLAS, cuDNN etc?

Some of the libraries are being worked on by the core developers, but since we are few, contributions from others wouldn't harm!

> I wonder if chipStar can just become the CUDA runtime on these open source drivers (by providing an OpenCL backend running atop the RustiCL driver)

Yes, this is the intention. We try to keep the number of required OpenCL extensions low and optional (based on the CUDA/HIP kernels compiled) to enable wide coverage on the supported OpenCL platforms where chipStar can run (at least some CUDA/HIP kernels).
