### ISSUE TITLE
Warnings when running benchmark

### ISSUE THREAD

**Issue by jjennychen** [CHIP-SPV/chipStar#525]
When compiling the **xlqc-hip** benchmark, we got the following warning:
```
warning: Linking two modules of different data layouts: '/tmp/crys-df724a/crys-generic.o' is '' whereas 'llvm-link' is 'e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024'

warning: Linking two modules of different data layouts: '/tmp/cints-80b18c/cints-generic.o' is '' whereas 'llvm-link' is 'e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024'

/usr/bin/ld: warning: /tmp/basis-32a62a.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```

To reproduce the warning, please refer to the steps in #510, replace the "bh-hip" with "xlqc-hip", and then do `module load gsl` before compiling. The warning should then appear at the end of the compilation.

Thank you!

**Comment by linehill** [comment]
The data layout warning is confirmed. Under the hood of the `hipcc`, the warnings are emitted when `llvm-link` links together a non-empty LLVM bitcode file followed by empty bitcode files. To me the warning seems excessive as linking something with empty input should obviously not have any data layout/ABI concerns.

I didn't see the /usr/bin/ld warning. Perhaps, because I have newer ld (2.38).

**Comment by jjennychen** [comment]
I see! Thank you so much!!
