### ISSUE TITLE
JIT Failures after updating to latest IGC 

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#725]
I use the following script for building and installing the latest intel-compute-runtime:
https://github.com/pvelesko/intel-compute-runtime-build 

After installing it:

```
╰─$ ./samples/0_MatrixMultiply/MatrixMultiply
Device name Intel(R) Arc(TM) A380 Graphics
MatrixMultiply: ./lib/SPIRV/SPIRVToLLVMDbgTran.cpp:1076: llvm::DIFile* SPIRV::SPIRVToLLVMDbgTran::getFile(SPIRV::SPIRVId): Assertion `SourceArgs.size() == OperandCount && "Invalid number of operands"' failed.
CHIP error [TID 7664] [1702111633.094515022] : Program BUILD LOG for device #0:Intel(R) Arc(TM) A380 Graphics:
IGC: Internal Compiler Error: Abnormal termination

CHIP error [TID 7664] [1702111633.094554951] : hipErrorNotInitialized (CL_BUILD_PROGRAM_FAILURE ) in /home/pvelesko/space/chipStar/main/src/backend/OpenCL/CHIPBackendOpenCL.cc:739:compile

CHIP error [TID 7664] [1702111633.094599766] : Caught Error: hipErrorNotInitialized
HIP API error
```

Going back to using old IGC resolves the issue

**Comment by linehill** [comment]
> `... Assertion SourceArgs.size() == OperandCount && "Invalid number of operands"' failed.`

Looks like a llvm-spirv bug that manifests in some of its branches. The buggy assertion can be found in for example in the [LLVM-16 branch](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/d1c69c3365dffed67124eb1692cb941cbae5bb2e/lib/SPIRV/SPIRVToLLVMDbgTran.cpp#L1328) which it expects all `OpExtInst ... DebugSource ...`  instructions to have [two](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/d1c69c3365dffed67124eb1692cb941cbae5bb2e/lib/SPIRV/libSPIRV/SPIRV.debug.h#L297) operands (`OperandCount`). This does not seem right respect to the debug info [spec](https://registry.khronos.org/SPIR-V/specs/unified1/OpenCL.DebugInfo.100.html#_compilation_unit) which states the DebugSource instructions take *one operand at minimum* (counted after the OpExtInst’s instruction operand). The assertion and the operand count seems to be corrected in other branches like [llvm_release_150](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/6b82481abc6df8de5b67c72ba1da57bcb58b75b0/lib/SPIRV/SPIRVToLLVMDbgTran.cpp#L1650) and [llvm_release_170](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/52b3a5f12d23ce0145fc8e0b8882e5d9bb31c664/lib/SPIRV/SPIRVToLLVMDbgTran.cpp#L1654).

It could be that the assertion gets triggered because the SPIR-V is generated with a llvm-spirv version that produces `OpExtInst … DebugSource` instructions with single operand. At least the latest llvm-spirv from llvm_release_170 branch does this.

**Comment by pvelesko** [comment]
I built using LLVM-14 provided by apt. According to intel-compute-runtime build instructions, LLVM-14 is the supported version and LLVV-SPIRV-Translator should match versions. Perhaps the revision from apt is just a bit behind. So overall, not related to igc

**Comment by linehill** [comment]
Found out by chance that the `-gdwarf-4` option has an effect on the debug info generated for device. This option is set on in debug builds of the chipStar and it appears in the compilation of HIP samples.

On LLVM-17, `-gdwarf-4` generates `OptExtInst … DebugSources` instructions with a single operand which triggers the buggy assertion. On the other hand, `-g` generates `OptExtInst … DebugSources` instructions with two operands. 

So we might dodge the assertion by avoiding using the `-gdwarf-#` option in the chipStar.

**Comment by pvelesko** [comment]
This option was originally introduced because without it there was some issue using gdb. Perhaps it's no longer necessary

**Comment by pvelesko** [comment]
Ran into another issue in IGC https://github.com/intel/intel-graphics-compiler/issues/310 

but overall, this is resolved for us.
